export const AUTH_ACTION_TYPES = {
	LOGIN: "LOGIN",
	SET_LOADING_LOGIN: "SET_LOADING_LOGIN",
	LOGOUT: "LOGOUT",
	SET_LOADING_SIGNUP: "SET_LOADING_SIGNUP",
	SET_LOADING_GET_USER: "SET_LOADING_GET_USER",
	GET_USER: "GET_USER",
};
