export const BOARD_DETAIL_ACTION_TYPES = {
	SET_LOADING_GET_DETAIL: "SET_LOADING_GET_DETAIL",
	GET_DETAIL: "GET_DETAIL",
	SET_LOADING_ADD_ITEM: "SET_LOADING_ADD_ITEM",
	ADD_ITEM: "ADD_ITEM",
	EDIT_ITEM: "EDIT_ITEM",
	EDIT_BOARD: "EDIT_BOARD",
};
