export const DASHBOARD_ACTION_TYPES = {
	GET_TEMPLATE_COLUMNS: "GET_TEMPLATE_COLUMNS",
	SET_LOADING_GET_TEMPLATE_COLUMNS: "SET_LOADING_GET_TEMPLATE_COLUMNS",
	TOGGLE_REALTIME: "TOGGLE_REALTIME",
	SET_LOADING_EXPORT: "SET_LOADING_EXPORT",
	SET_LOADING_IMPORT: "SET_LOADING_IMPORT",
};
