export const DASHBOARD_ACTION_TYPES = {
	TOGGLE_REALTIME: "TOGGLE_REALTIME",
	SET_LOADING_BOARD: "SET_LOADING_BOARD",
	GET_BOARD: "GET_BOARD",
	ADD_BOARD: "ADD_BOARD",
	SET_LOADING_ADD_BOARD: "SET_LOADING_ADD_BOARD",
};
