export const PROFILE_ACTION_TYPES = {
	SET_LOADING_UPDATE_PROFILE: "SET_LOADING_UPDATE_PROFILE",
	UPDATE_PROFILE: "UPDATE_PROFILE",
	SET_LOADING_UPDATE_PASSWORD: "SET_LOADING_UPDATE_PASSWORD",
	UPDATE_PASSWORD: "UPDATE_PASSWORD",
};
